### PR TITLE
m13 continuous development

### PR DESCRIPTION
**Pull request by iamabhutta**
starting w sp24 version of slides (updated slide 1 only) = this was m13 in spring
Will need to look at the feedback and revise the slides before Wed (10/16).

### CODE REVIEW

**Comment by mwand** [comment]
I have some ideas for turning this into a coherent story. I will work on it
tonight.

**Comment by mwand** [comment]
Pushed a rough version of slides.   I hid all the slides that I either didn't understand or was embarrassed to show.   Tried to turn it into a coherent story about how automated QA was the key to agile, and here are how you could do the same thing for later development changes.  

Tried to make the slides tell the story; didn't attempt to update the scripts.

The formatting is completely wedged.  It will take a lot of effort to make the formatting consistent with what we've used elsewhere.  I'm not sure I will have the time or the expertise to do this.  (Do we have any TAs who are PPT experts?)

**Comment by iamabhutta** [comment]
I saw a few slides hidden in pptx but they show up in pdf. Did you not update the pdf file? 
I mostly agree with the list of slides that are hidden, except for a few. See below. 
Note: Slide numbers are from pptx file

Slide 15/16 (CI in practice) can stay. They basically show a typical yml file and how it is used. They are using it in IP2.
S17/18 can remain hidden.
S21 has some useful bullet points, perhaps move those to another slide like S20 and then delete S21.
S24 is an example of fast CI at large scale. It is a good slide to keep
S37/38/44/45 can go

**Comment by mwand** [comment]
Ahh, no I didn't update the pdf, sorry for the confusion.

I've unhidden the few files you suggested.  I've also added another section at the end talking about different strategies for allocating our testing resources.  This starts at s41. Old s24 is now s43.  I also rewrote the slides about FB release, not sure if these were in the previous commit.

Will put reformatting on the list for next semester.

**Comment by iamabhutta** [comment]
I actually like the facebook pre-2016 slide (I see that you turned it into a slide with a lot of text). That's fine but I would like to use the image too (I have added it back as hidden slide). 
Also Slide 47 (allocate testing resources) could use some notes.
Rest lgtm

**Pull request merged**
