### PR TITLE
module07-agile

### PR DESCRIPTION
**Pull request by iamabhutta**
starting pr with sp24 slides (no updates yet except slide 1)

### CODE REVIEW

**Comment by iamabhutta** [comment]
Updated with all the changes. We can review it again over next couple of days and update as needed before merging

**Comment by mwand** [comment]
Hope you like it.   Should now be ready for merge.

**Comment by iamabhutta** [comment]
Your last built failed. I am rebuilding it and then merging!

**Comment by mwand** [comment]
Oh cr*p, I see I accidentally pushed my Gemfile.lock.   Sorry.

**Pull request merged**
