### PR TITLE
initial commit for M06

### PR DESCRIPTION
**Pull request by mwand**
lots of updating in slides; activities and examples largely unchanged.

### CODE REVIEW

**Comment by iamabhutta** [comment]
Initial feedback:
Timing of animation is weird in slides 8-10. why are "3 resolved" showing up at the start?
We had "odds and ends" (slide 38) as optional in the past.
Do we need self-ticking clock (Slide 43)?
For Slide44, I suggest remove everything except the link to module /activity page. Let's leave instructions in one place. We want to avoid having these updated in two places.
I will take another pass at new slides in the evening ... need to think thru these.

**Comment by mwand** [comment]
Adeel wrote:

>Timing of animation is weird in slides 8-10. why are "3 resolved" showing up at the start?

Removed extra slide

>We had "odds and ends" (slide 38) as optional in the past.

Changed title to "Optional Material"

> Do we need self-ticking clock (Slide 43)?

Removed (sniff!).  I really wanted to demonstrate that the self-ticking clock from m05 was easy to build.  I've left the slide in at the very end, after the LO's.  But you're right it doesn't fit in, and it felt weird every time I taught it.

> For Slide44, I suggest remove everything except the link to module /activity page. Let's leave instructions in one place. We want to avoid having these updated in two places.

Agreed.  We should have a boilerplate slide that we can use for every module.

**Comment by iamabhutta** [comment]
Two things:
A. Here is the link for Canvas assignment for Team formation:
https://northeastern.instructure.com/courses/188155/assignments/2447002

B. Here is my detailed take on slides:
Slide 7: Waiting is same thing as pending?
Slide 8 animation still has "3 resolved and one waiting" displayed before first click.
Slide 9 animation: red stars are showing before first click
Slide 13: Suggest adding this: 
0. Someone calls example(n)
1. {old text is fine} ... then add "this prints console.log"
2. old text is fine
3. {old text is fine} then add: "in other words, yellow code is blocked or does not execute."
4. {old text is fine} then add:  in other words, control returns from the function
5. caller continues

Slide 14: important point to add is: "more code" gets executed while p1 is waiting.
Question is, when do we switch to p1? After p0 is completed (i.e., more code finishes)

Slide 15 might have an error. It is missing: "returning to main" which will be printed before "main finished\n"

Slide 17: Suggest adding text that says something like "we intentionally serialized this order"

Slide 18: An important point that's missing here is, how do we use parallel processing or concurrency? We can create many promises (not force serial execution) and rely on browser to execute waiting promises independently. Promise all allows us to pause some computation until all promises are fulfilled.

Slide 21: Suggesting adding this to last bullet - i.e., control returns from this function with pending promise.

Slide 25: You can add another note in box that says, the responses may be received out of order.

Rest LGTM

**Comment by mwand** [comment]
Aagh!  markdown has messed with the numbering.  What do your "5. good" and
"6. good.." refer to?  Can you resend with some triple backticks so I can
see exactly what you mean?

**Comment by iamabhutta** [comment]
It messed up all of my comments and numbering. I have updated it above.

**Comment by mwand** [comment]
Newly formatted comments were much better, thanks.
I see we now have some merge conflicts associated with this branch.  Can you resolve them when you merge?

**Comment by abhutta0** [comment]
Are updates done? I can review again and try to fix merge conflicts

**Comment by mwand** [comment]
Updated script for slide #7.

**Pull request merged**
