### PR TITLE
m01-1-introductions

### PR DESCRIPTION
**Pull request by iamabhutta**
updated for fa24

### CODE REVIEW

**Comment by mwand** [comment]
I've made some small edits on the source (will push these shortly).  I notice that the "Communications" slide does not include info on contacting the instructors.    This is an issue for me, because messages sent to me from Canvas often do not get through.  See Slide 9 in the attached ppt.  You can put this in the repo version (maybe retitled to "Special Notes: Communicating with Professor Wand" or something like that), or I can continue to add this slide to the repo version when I give the lecture.

Actually, the last two bullets on that slide might be useful for you, too.

[Module 01.1 Course Introduction (with Wand communication).pptx](https://github.com/user-attachments/files/16614370/Module.01.1.Course.Introduction.with.Wand.communication.pptx)

**Comment by mwand** [comment]
bah, my local build succeeds; github build fails.  I think it has something to do with Gemfile.lock.  Will investigate shortly.

**Comment by iamabhutta** [comment]
Once you are done with your updates, I can add a version of that slide in the main slidedeck.

**Comment by iamabhutta** [comment]
perhaps copy gemfile.lock from main repo?

**Pull request closed without merging**
