### PR TITLE
M05 Design Patterns - intial slides from sp24

### PR DESCRIPTION
**Pull request by iamabhutta**

### CODE REVIEW

**Comment by iamabhutta** [comment]
@JoyMitra do we need to discuss any other design patterns (apart from observer and singleton) that can help students in project?

**Comment by mwand** [comment]
Is this ready for final review?

**Comment by iamabhutta** [comment]
Yes, Joydeep reviewed it and said. it looks good (wrt new codebase).

**Comment by mwand** [comment]
lgtm.

**Pull request merged**
