### PR TITLE
final project deliverables

### PR DESCRIPTION
**Pull request by iamabhutta**
updated for this semester. Also added details for demos.
To discuss: should we make report as 5% and increase the grade for testing? Perhaps say something about UI testing?
How about individual reflection. Do we really need it?

### CODE REVIEW

**Comment by mwand** [comment]
> updated for this semester. Also added details for demos.
> To discuss: should we make report as 5% and increase the grade for testing? 
> Perhaps say something about UI testing?

Will check diffs tomorrow & think about the other two.

> How about individual reflection. Do we really need it?

Yes, I am strongly in favor of keeping it, both for the students' benefit and ours.

**Comment by mwand** [comment]
tweaked project-grading.md.  Removed line about "script for manual grading of UI", re-added line about "manual inspection of tests indicates good-faith effort".   Probably other things, too.  Also added Spring 24 version to the repo for easy diffing-- you should remove this before merging, of course.

**Comment by iamabhutta** [comment]
I am not sure if I see all the changes (other than the ones in Testing part of rubric)! Is that all? 
Do we want to talk about cypress tests?
Also, we should leave "10% for additional features" as is and not add "optional" there - this will cause students to think that they need to implement the optional features, which they don't!

**Comment by mwand** [comment]
> I am not sure if I see all the changes (other than the ones in Testing part of rubric)! Is that all? 
Yes, I think those were the only places I touched.

> Do we want to talk about cypress tests?
No-- we didn't teach them enough to write them.

> Also, we should leave "10% for additional features" as is and not add "optional" there - this will cause students to think that they need to implement the optional features, which they don't!

But some of the TAs seemed to think that this meant that they wouldn't get any credit for things marked as "extensions".

**Comment by iamabhutta** [comment]
That is correct. They don't get extra credit for completing "extension". We use it as a replacement if they can't finish some essential or desirable work. We can use that for curving their final grades but that's not something we need to specify in rubric

**Pull request merged**
