### PR TITLE
project plan document

### PR DESCRIPTION
**Pull request by iamabhutta**
sp24 version with new updates.
Need to update the example labelled. "TOBEUPDATED"

### CODE REVIEW

**Comment by iamabhutta** [comment]
Now its updated!

**Comment by mwand** [comment]
> we expect that the feature that you propose will be at least as
  complex as the feature implemented in the individual assignments.

This seems like a fairly low bar :).   Should we suggest that they
propose multiple features if the features are not hard enough
individually? 

> Add Session management for your project

What does this mean?

> Use Chakra UI Library for components and make your UI accessible

These are two different things.  One could do one but not the other.
If the goal is to make the UI accessible, then it should involve
finding some tool to test the accessbility of the codebase,
identifying the deficiencies, and then fixing as many of them as
possible within the project timeline.

Finding the tool and running it on the codebase should be done prior
to submitting the project plan; otherwise the PP would be unacceptably
vague.  Better wording, maybe:

* Assess the accessibility of the UI, using some external tool, and
  then improve it.  (Be sure to do the assessment prior to
  submitting the Preliminary Project Plan, and be specific in your conditions of satisfaction).

Or maybe just:

* Improve the accessibility of the UI for some class of user (eg: screen-reader user, low-vision user, user with color blindness).  
https://www.tpgi.com/how-write-user-stories-accessibility-requirements/



> Support additional persistence options: (e.g. Firebase, Supabase,
  Postgres + GraphQL), allow users to register and save a profile
  (e.g. using Auth0)

I think this was supposed to be two different bullets.

Maybe better words for the first half: 
 
* Modify the code so that it is easy to switch to other persistence options (eg ....).

(I wonder what the acceptance criteria for this would be)


Maybe better words for the second half:

* Allow users to save a persistent profile, using some SSO tool for  authorization (eg Auth0, github, google).

Possible additional bullets (with subbullets)


* Improve the quality of the tests
** add more comprehensive end-to-end tests
** assess the quality of the unit tests and improve them
*** use Stryker to find untested branches
*** improve the quality of the tests involving mocks

(Again, what might the acceptance criteria be?)

* The codebase includes skeleton code for REST, WebSockets, and a
persistent database.   Propose some cool app can you build with this
infrastructure.

... moving on to later in the document:

>  You should include three different user stories to describe how
   users will interact with your feature.

First, the number "three" seems arbitrary in this context, especially given the kind of thing suggested in the bullets.

Second, what does this even mean if the project is to improve the *quality* of
the code (eg, testability or extensibility)?

https://tetralogical.com/blog/2022/05/26/how-to-write-user-stories-for-accessibility/
https://www.tpgi.com/how-write-user-stories-accessibility-requirements/

Here's the best source I've found about "technical" user stories:

https://lizkeogh.com/2008/09/10/feature-injection-and-handling-technical-stories/

**Comment by iamabhutta** [comment]
Please go ahead and update as needed.

**Comment by mwand** [comment]
Expanded list of suggested projects.

Reordered paragraphs in many places to improve flow.

Clarified description of Sprint -1, moved it to a more logical place in the document flow.  Also added suggestion that teams work with their mentors and share project plan with them *before* the plan is due.  (I think this is important to avoid dead time)

**Comment by iamabhutta** [comment]
lgtm

**Pull request merged**
